name: Publish
on:
  push: #监听 push 事件
    branches: [main]
  pull_request:
    branches: [main]
jobs: # 定义任务
  publish: #定义一个名为 publish 的任务
    runs-on: ubuntu-latest # 运行环境 ubuntu-latest
    permissions:
      contents: read
      packages: write # 允许发布 npm 包到 GitHub packages
    steps: 
      - name: Checkout code # 第一步：拉取代码
        uses: actions/checkout@v4 # 官方 GitHub Action
      - name: Set up Node.js # 第二步： 设置Node.js h
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies #第三步：安装依赖
        run: npm install
      - name: Build project #构建项目
        run: npm run build
      - run: |
          echo "@chreeylxq:https://npm.pkg.github.com/" > build/.npmrc 
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN}}" >> build/.npmrc
      - run: npm publish 
        working-directory: ./build
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          